@host = http://localhost:8080/api
@accessToken = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZ2YVBwMVdwaFk5WDBwX2h1RmJnaSJ9.eyJpc3MiOiJodHRwczovL2Rldi0ycXkxeWI1My51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDgzMTU2NDMxMTk2ODAwMzI5NDUiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9kZXYtMnF5MXliNTMudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2MzEzMDAwOSwiZXhwIjoxNjYzMjE2NDA5LCJhenAiOiJwb0FVYjNZT0ZXeVdlYmJlNUc0c2FvZ2w3S016dm1RbyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.LZV_rLJXsNXR_rqLvulxqXJTnB9F1AIc1A8o60V3mTY9z5Y35tzDr7kbyYTCgcOO7Y3pAN1m97pGdiVY2WP9mfYRPiC3kvPVCBfBfpEJouDJtbqHBmvfCcgGObiD-zNfRHsmALJjGUknJ-6SOvazLBUA1cdSuTVkRpZdCqDA9iW5-eFWxfekb4IELgzplW7gPovN6Cj9TV3pRceteecK_S9CT6Xmm7BJ3wGK2lCsaHM54DzyI8sPLhQEDDRIVfeI_O7q9SyzglBQvbCqbBorF1a4FtXNZquedpiFyveuRhk08Nk1pyNyspXsZbxgHxyF0e3UA6NgS7eWnCcxNMGp7g

# Categories

GET {{host}}/categories HTTP/1.1
Authorization: {{accessToken}}

### 

POST {{host}}/categories HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
    "name": "Food"
}

###

PATCH {{host}}/categories/631afe5da85e505fcda86bb8 HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
    "name": "Updated 2",
    "description": "Wow",
    "createdById": "google-oauth2|108315643119680032945"
}

###

DELETE  {{host}}/categories/6320b0e1361a75a01bb078a3 HTTP/1.1
Authorization: {{accessToken}}

###

# Transactions

GET {{host}}/transactions?pageSize=20&fromDate=2022-09-05T17:00:00.000Z&toDate=2022-09-09T17:00:00.000Z HTTP/1.1
Authorization: {{accessToken}}

###

POST {{host}}/transactions HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
    "amount": 1024000,
    "transactionDate": "2022-09-11T08:50:37.299Z",
    "name": "Vialand",
    "category": "631afe5da85e505fcda86bb8",
    "income": true
}

###

GET {{host}}/transactions/analytics?&fromDate=2022-09-05T17:00:00.000Z&toDate=2022-09-09T17:00:00.000Z HTTP/1.1
Authorization: {{accessToken}}
