@host = http://localhost:8080/api
@accessToken = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZ2YVBwMVdwaFk5WDBwX2h1RmJnaSJ9.eyJpc3MiOiJodHRwczovL2Rldi0ycXkxeWI1My51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDgzMTU2NDMxMTk2ODAwMzI5NDUiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9kZXYtMnF5MXliNTMudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2MjgyMjc0OCwiZXhwIjoxNjYyOTA5MTQ4LCJhenAiOiJwb0FVYjNZT0ZXeVdlYmJlNUc0c2FvZ2w3S016dm1RbyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.bjw16W2Atc4cEaf4u4TuaTnsXGqXieQ-QR_1vOaStv-G7Btig2HAdqIxV9mS8fFeYGMHk_gOY38zaPDQ3vDLsjmwT9f5HLQLGuvKOWp8oMJ3s_j-e6TkyR4HfgoPQb5ntDsW9NOL7uk6oNQy3uP7b7DmkBX0RugiIr8JxJOqSsxNoAeNJAxBx61AHVzZ5yxEEBMQ_mbx-4l4E_y695sP-DcZwLo6x06s5E21B2a_NRp5yBSGX9pFURcgQbEn3qKjd_M94yi_jg3J5LRKt71NX3y0WlavbQuzrL1fSGlE3d1OqPBJACEAwJMujst0LaKZ9K6E4KK-FwhzEY9a_JEA4Q

# Categories

GET {{host}}/categories HTTP/1.1
Authorization: {{accessToken}}

### 

POST {{host}}/categories HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
    "name": "Food"
}

###

# Transactions

GET {{host}}/transactions?pageSize=20&fromDate=2022-09-05T17:00:00.000Z&toDate=2022-09-09T17:00:00.000Z HTTP/1.1
Authorization: {{accessToken}}

###

POST {{host}}/transactions HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
    "amount": 1024000,
    "transactionDate": "2022-09-11T08:50:37.299Z",
    "name": "Vialand",
    "category": "631afe5da85e505fcda86bb8",
    "income": true
}

###

GET {{host}}/transactions/analytics?&fromDate=2022-09-05T17:00:00.000Z&toDate=2022-09-09T17:00:00.000Z HTTP/1.1
Authorization: {{accessToken}}
